from enum import Enum
from pydantic import BaseModel, Field
from typing import List, Optional

# --- Planner Schema ---
class PlannerOutput(BaseModel):
    original_question: str = Field(description="The original user query")
    sub_questions: List[str] = Field(description="List of distinct, specific sub-questions to investigate")

# --- Structured Failure Path Status ---
class SearchStatus(str, Enum):
    SUCCESS = "SUCCESS"
    NO_RESULTS = "NO_RESULTS"
    RATE_LIMITED = "RATE_LIMITED"
    PAYWALLED = "PAYWALLED"
    TIMED_OUT = "TIMED_OUT"
    ERROR = "ERROR"

# --- Researcher Schema (Programmatic) ---
class SearchSource(BaseModel):
    title: str = Field(description="Title of the source webpage")
    url: str = Field(description="URL of the source webpage")
    content: str = Field(description="Primary content, raw markdown excerpt, or text snippet from the webpage")
    raw_content: Optional[str] = Field(default=None, description="Full raw markdown content from the webpage if available")

class ResearcherOutput(BaseModel):
    sub_question: str = Field(description="The sub-question that was researched")
    sources: List[SearchSource] = Field(default_factory=list, description="List of search result sources containing content and URLs")
    status: SearchStatus = Field(default=SearchStatus.SUCCESS, description="Structured execution status of the search")
    error_message: Optional[str] = Field(default=None, description="Error or diagnostic message if not SUCCESS")

# --- Supervisor Schema ---
class SubQuestionReview(BaseModel):
    sub_question: str = Field(description="The sub-question under review")
    is_answered: bool = Field(description="Whether the search findings sufficiently answer the sub-question")
    sources_sufficient: bool = Field(description="Whether reliable, non-empty sources were found")
    feedback: str = Field(description="Specific feedback or evaluation rationale for this sub-question")
    refined_query: Optional[str] = Field(
        default=None,
        description="Targeted refined search query if revision is required"
    )

class SupervisorOutput(BaseModel):
    approved: bool = Field(description="True if all sub-questions are answered or no further pass is justified")
    reasoning: str = Field(description="Explanation of the overall evaluation")
    sub_question_reviews: List[SubQuestionReview] = Field(
        default_factory=list,
        description="Per sub-question review breakdown"
    )

# --- Budget & Constraint Schema ---
class BudgetConfig(BaseModel):
    max_sub_questions: int = Field(default=3, description="Maximum number of sub-questions generated by Planner")
    max_searches_per_sub_question: int = Field(default=2, description="Maximum search calls allowed per sub-question")
    max_sources_per_domain_sub_q: int = Field(default=1, description="Maximum allowed sources from a single domain per sub-question")
    max_total_tokens: int = Field(default=12000, description="Estimated total token ceiling")
    wall_clock_timeout_seconds: float = Field(default=60.0, description="Maximum wall-clock execution time in seconds")
    max_revisions: int = Field(default=1, description="Maximum number of revision loops allowed (exact-once)")

# --- Writer Schema ---
class ReportSection(BaseModel):
    section_title: str = Field(description="Title of this section")
    section_content: str = Field(description="Content of this section with inline markdown citations like [1], [2] pointing to references in the citations list")

class WriterOutput(BaseModel):
    title: str = Field(description="Title of the research report")
    summary: str = Field(description="A brief executive summary of the entire report")
    sections: List[ReportSection] = Field(description="List of detailed sections containing content and citations")
    citations: List[str] = Field(description="List of all unique source URLs referenced in the sections. The index corresponds to the inline citations [1], [2], etc.")
    validation_warnings: List[str] = Field(default_factory=list, description="Warnings if any citations in the text are unverified or mismatched")

# --- Run Status & API Schemas (Phase 5) ---
class RunStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"

class TraceStepSchema(BaseModel):
    step_index: int = Field(description="Order index of this execution step")
    agent_name: str = Field(description="Name of the agent (Planner, Researcher, Supervisor, Writer)")
    input_data: Optional[dict] = Field(default=None, description="Input payload passed to the agent")
    output_data: Optional[dict] = Field(default=None, description="Output payload produced by the agent")
    tools_called: List[str] = Field(default_factory=list, description="List of tools invoked in this step")
    tokens_used: int = Field(default=0, description="Tokens consumed during this step")
    latency_ms: float = Field(default=0.0, description="Execution duration in milliseconds")
    created_at: Optional[str] = Field(default=None, description="Timestamp when step was recorded")

class ResearchRequest(BaseModel):
    question: str = Field(..., min_length=3, description="The research query or topic to investigate")
    timeout: Optional[float] = Field(default=60.0, description="Wall-clock execution ceiling in seconds")
    max_sub_questions: Optional[int] = Field(default=3, description="Maximum sub-questions to investigate")
    max_tokens: Optional[int] = Field(default=16000, description="Total token budget limit")

class ResearchResponse(BaseModel):
    run_id: str = Field(description="Unique ID for this research session")
    status: RunStatus = Field(description="Initial status of the submitted research job")
    message: str = Field(description="Informational status message")

class ResearchStatusResponse(BaseModel):
    run_id: str = Field(description="Unique ID for this research session")
    question: str = Field(description="The original user query")
    status: RunStatus = Field(description="Current status of the research workflow")
    execution_time_sec: Optional[float] = Field(default=0.0, description="Total execution time in seconds")
    total_tokens: Optional[int] = Field(default=0, description="Total exact tokens used across all agents")
    total_searches: Optional[int] = Field(default=0, description="Total search API calls made")
    revision_count: Optional[int] = Field(default=0, description="Total revision passes requested by Supervisor")
    report: Optional[WriterOutput] = Field(default=None, description="Completed research report with verified citations")
    error_message: Optional[str] = Field(default=None, description="Error message if the workflow failed")

