from pydantic import BaseModel, Field
from typing import List, Optional

# --- Planner Schema ---
class PlannerOutput(BaseModel):
    original_question: str = Field(description="The original user query")
    sub_questions: List[str] = Field(description="List of distinct, specific sub-questions to investigate")

# --- Researcher Schema (Programmatic) ---
class SearchSource(BaseModel):
    title: str = Field(description="Title of the source webpage")
    url: str = Field(description="URL of the source webpage")
    content: str = Field(description="Primary content, raw markdown excerpt, or text snippet from the webpage")
    raw_content: Optional[str] = Field(default=None, description="Full raw markdown content from the webpage if available")

class ResearcherOutput(BaseModel):
    sub_question: str = Field(description="The sub-question that was researched")
    sources: List[SearchSource] = Field(description="List of search result sources containing content and URLs")

# --- Supervisor Schema ---
class SubQuestionReview(BaseModel):
    sub_question: str = Field(description="The sub-question under review")
    is_answered: bool = Field(description="Whether the search findings sufficiently answer the sub-question")
    sources_sufficient: bool = Field(description="Whether reliable, non-empty sources were found")
    feedback: str = Field(description="Specific feedback or evaluation rationale for this sub-question")
    refined_query: Optional[str] = Field(
        default=None,
        description="Targeted refined search query if revision is required"
    )

class SupervisorOutput(BaseModel):
    approved: bool = Field(description="True if all sub-questions are answered or no further pass is justified")
    reasoning: str = Field(description="Explanation of the overall evaluation")
    sub_question_reviews: List[SubQuestionReview] = Field(
        default_factory=list,
        description="Per sub-question review breakdown"
    )

# --- Budget & Constraint Schema ---
class BudgetConfig(BaseModel):
    max_sub_questions: int = Field(default=3, description="Maximum number of sub-questions generated by Planner")
    max_searches_per_sub_question: int = Field(default=2, description="Maximum search calls allowed per sub-question")
    max_total_tokens: int = Field(default=8000, description="Estimated total token ceiling")
    wall_clock_timeout_seconds: float = Field(default=60.0, description="Maximum wall-clock execution time in seconds")
    max_revisions: int = Field(default=1, description="Maximum number of revision loops allowed (exact-once)")

# --- Writer Schema ---
class ReportSection(BaseModel):
    section_title: str = Field(description="Title of this section")
    section_content: str = Field(description="Content of this section with inline markdown citations like [1], [2] pointing to references in the citations list")

class WriterOutput(BaseModel):
    title: str = Field(description="Title of the research report")
    summary: str = Field(description="A brief executive summary of the entire report")
    sections: List[ReportSection] = Field(description="List of detailed sections containing content and citations")
    citations: List[str] = Field(description="List of all unique source URLs referenced in the sections. The index corresponds to the inline citations [1], [2], etc.")
